### PR TITLE
Missing commits from v0.3.0

### PR DESCRIPTION
**Pull request by sunesimonsen**
The current release is made on the v0.3.0 tag. Master is not up to date with the changes on that branch.

### CODE REVIEW

**Comment by sunesimonsen** [comment]
Mhh this should actually go in before the branch you just merged. Maybe it easier for you to fix the problem by rebasing and force pushing master.

**Comment by kossnocorp** [comment]
@sunesimonsen right, sorry I'm completly fucked up with master branch, thank you for help!

**Comment by sunesimonsen** [comment]
NP I'm very happy with your plugin, so thanks for contributing that!

**Comment by kossnocorp** [comment]
@sunesimonsen cool! Btw do you know about https://github.com/kossnocorp/static-files-webpack-plugin?

**Comment by sunesimonsen** [comment]
Yes that is what I'm trying to fix, you'll get another PR in a moment :-)

**Comment by kossnocorp** [comment]
tmux___users_koss_src_kossnocorp_static-file-loader

**Comment by sunesimonsen** [comment]
Thank a lot!

**Pull request closed without merging**
